#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

limit_sub() {
  declare desc="executes a limit subcommand"
  local name="$1"
  shift
  "$PLUGIN_AVAILABLE_PATH/config/subcommands/$name" "config:$name" "$@"
}

limit_all() {
  declare desc="Backwards compatible function for plugin use"
  [[ "$1" == "config" ]] || set -- "config" "$@"
  if [[ -n "$DOKKU_CONFIG_EXPORT" ]]; then
    config_export app "$@"
    return 0
  fi

  "$PLUGIN_AVAILABLE_PATH/config/commands" "$@"
}

limit_set() {
  declare desc="set value of given config var"
  config_sub set "$@"
}
