#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

cd $(dirname "$0")
make build-in-docker || exit 1
make src-clean || exit 1
mkdir -p "${DOKKU_LIB_ROOT}/data/limit"
echo "installed/updated dokku limit plugin"